sistema/Models/ErrorViewModel.cs
using System;

namespace sistema.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

sistema/Models/NoticiaModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace sistema.Models
{
    public class Noticia
    {
        [Key]
        public long NoticiaID { get; set; }

        [Required]
        [Display(Name = "Titulo")]
        [DataType(DataType.Text)]
        public string Titulo { get; set; }

        [Required]
        [Display(Name = "Subtitulo")]
        [DataType(DataType.Text)]
        public string Subtitulo { get; set; }

        [Required]
        [Display(Name = "Corpo")]
        [DataType(DataType.Text)]
        public string Corpo { get; set; }
        
        [Display(Name = "Comentarios")]
        public List<Comentario> Comentarios { get; set; }
    }
    public class Comentario
    {
        [Key]
        public long ComentarioID { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [StringLength(30, MinimumLength = 3)]
        public string Autor { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [StringLength(20, MinimumLength = 3)]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [StringLength(100, MinimumLength = 5)]
        public string ComentarioTexto { get; set; }
        public long NoticiaID { get; set; }
        public Noticia Noticia { get; set; }
    }
}

sistema/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using sistema.Data;
using sistema.Models;

namespace sistema.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            var ctx = new SistemaContext();
            
            var model = from noticias in ctx.noticias
                select new Noticia {
                    NoticiaID = noticias.NoticiaID,
                    Titulo = noticias.Titulo
                };

            return View(model.ToList());
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

sistema/Controllers/NoticiaController.cs
using System.Diagnostics;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using sistema.Data;
using sistema.Data.Methods;
using sistema.Models;

namespace sistema.Controllers
{
    public class NoticiaController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        public NoticiaController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index(long ID)
        {
            using (var ctx = new SistemaContext())
            {
                var gcn = new GetNoticia();
                return View(gcn.Get(ID));
            }
        }
        public IActionResult Comentarios(long id, string msg)
        {
            var gct = new GetComentarios();

            ViewBag.Message = msg;
            ViewData["comentarios"] = gct.Get(id);
            
            return View("Comentarios", gct.Get(id));
        }

        public IActionResult InserirComentario(long id, [Bind("Autor, Email, ComentarioTexto")] Comentario model)
        {
            var cmt = new InserirComentario();
            
            if (cmt.Insere(id, model.Autor, model.Email, model.ComentarioTexto) == true)
            {
                string msg = "Comentário adicionado com sucesso!";
                return RedirectToAction("Comentarios", new {id = id, msg});
            }
            else
            {
                string msg = "Não foi possível adicionar um comentário";
                return RedirectToAction("Comentarios", new {id = id, msg});
            }
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

sistema/Views/Home/Index.cshtml
@model IEnumerable<sistema.Models.Noticia>
@{
    ViewData["Title"] = "Home Page";
}

@foreach (var item in Model)
{
  <div class="card-group">
    <div class="card">
      <div class="card-body">
        <a id="home-index-card-group-title" class="card-title" asp-controller="Noticia" asp-action="Index" asp-route-id="@item.NoticiaID">@Html.DisplayFor(modelItem => item.Titulo)</a>
      </div>
    </div>
  </div>
}

sistema/Views/Noticia/Comentarios.cshtml
@using sistema.Models
@model IEnumerable<sistema.Models.Comentario>
@{
    ViewData["Title"] = "Comentarios";
}
<h2 style="color: white;">
    Escreva um comentário
</h2>
<strong style="color: orange;">@ViewBag.Message</strong>
<br>
<form asp-controller="Noticia" asp-action="InserirComentario" asp-route-id="@Model.Select(x => x.NoticiaID).FirstOrDefault()" style="color: white;">
    <div class="form-group">
        <label for="forInputNome">Nome</label>
        <input type="text" size="30" class="form-control" id="Autor" name="Autor" aria-describedby="nomeHelp" placeholder="Digite seu nome">
    </div>
    <div class="form-group">
        <label for="forInputEmail">Email</label>
        <input type="email" size="20" class="form-control" id="Email" name="Email" placeholder="Digite seu e-mail">
    </div>
    <div class="form-group">
        <label for="forInputComentario">Comentário</label>
        <input type="text" size="100" class="form-control" id="ComentarioTexto" name="ComentarioTexto" placeholder="Digite seu comentário">
    </div>
    <button type="submit" class="btn btn-primary">Comentar</button>
</form>
<br>
<br>
<h4 style="color: white;">
    Comentários
</h4>
@foreach (var item in ViewData["comentarios"] as List<Comentario>)
{
    <div class="card" style="text-align: justify">
        <div class="card-body">
            <h5 class="card-title">@item.Autor</h5>
            <p class="card-text">@item.ComentarioTexto</p>
        </div>
    </div>
}

sistema/Views/Noticia/Index.cshtml
@using sistema.Models
@model sistema.Models.Noticia
@{
    ViewData["Title"] = "Index";
}

<div class="container-sm" style="color: white; text-align: justify;">
    <h1>
        @Html.DisplayFor(c => c.Titulo)
    </h1>
    <br>
    <h3>
        @Html.DisplayFor(c => c.Subtitulo)
    </h3>
    <br>
    <p>
        @Html.DisplayFor(c => c.Corpo)
    </p>
    <br>
    @* @foreach (var item in ViewData["comentarios"] as List<Comentario>)
    {
        @item.Autor
    } *@
    <h5>
        <a asp-controller="Noticia" asp-action="Comentarios" asp-route-id="@Model.NoticiaID" style="color: white;">Veja os comentários desta notícia</a>
    </h5>
</div>

sistema/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sistema Notícias</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="bg-dark">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-sm">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sistema Notícias</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container" style="color: white;">
            &copy; 2021 - Sistema Notícias - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>